#!/bin/bash

PS3='Kérlek add meg a választásod:'
options=("Négyzetgyök kiszámoló" "Random jelszó generáló" "Kiírja a mai dátumot" "Fibonacci számsorozat" 
"Létezik-e?" "Mappa készítő" "Hatványozás" "Kilépés")
while getopts :r:n:df:e:k opt
do
	case $opt in
		n)
		   number=$OPTARG
		   square_root=`echo "scale=4; sqrt($number)" | bc`
		   echo "Az általad megadott számnak a négyzetgyöke $square_root"
		     ;;

		r)
		   pass_length=$OPTARG

		   for i in {1..5}; do (tr -cd '[:alnum:]' < /dev/urandom | fold -w${pass_length} | head -n 1); 
		   done

		   printf "$pass_output\n"
		     ;;

		"Kiírja a mai dátumot")
		   now=$(date)
		   echo "Mai dátum: $now"
		   ;;

		f)
		   n=$OPTARG
		   function fib
		   {
    		     x=0
		     y=1
		     i=2
		     echo "Fibonacci számsorozat eddig a számig $n :"
		     echo "$x"
		     echo "$y"
		     while [ $i -lt $n ]
		     do
			i=`expr $i + 1 `
			z=`expr $x + $y `
			echo "$z"
			x=$y
			y=$z
		     done
		    }
		    r=`fib $n`
		    echo "$r"
		     ;;

		"Létezik-e?")
		  echo "Add meg a fájl nevét"
		  read newfile1
	   	  if [ -f "$newfile1" ]
	  	  then
		  echo "Ilyen fájl létezik!"
		  else
		    echo "Ilyen fájl nem létezik!"
	          fi
		  ;;
		k)
		curl https://kontests.net/api/v1/all -o response.json
		n=$(cat response.json | jq ". | length")
		i=0
		while [ $i -lt $n ]
		do 
		cat response.json | jq .[$i].name | tr -d "\""
		cat response.json | jq .[$i].start_time | tr -d "\""
		echo
 		i=$(($i+1))
		done
		 ;;
		:)
		echo "$OPTARG vár értéket"
		exit
		;;
		*)
		echo "Érvénytelen paraméter!"
		exit
		esac
		done
