#!/bin/bash

PS3='Kérlek add meg a választásod:'
options=("Négyzetgyök kiszámoló" "Random jelszó generáló" "Kiírja a mai dátumot" "Fibonacci számsorozat" 
"Négyszög rajzoló" "Kilépés")
select opt in "${options[@]}"
do
	case $opt in
		"Négyzetgyök kiszámoló")
		   read -p "Adj meg egy számot: " number
		   square_root=`echo "scale=4; sqrt($number)" | bc`
		   echo "Az általad megadott számnak a négyzetgyöke $square_root"
		     ;;

		"Random jelszó generáló")
		   printf "\n"
		   read -p "Hány karakteres jelszót szeretnél?" pass_length
		   printf "\n"

		   for i in {1..5}; do (tr -cd '[:alnum:]' < /dev/urandom | fold -w${pass_length} | head -n 1); 
		   done

		   printf "$pass_output\n"
		     ;;

		"Kiírja a mai dátumot")
		   now=$(date)
		   echo "Mai dátum: $now"
		   ;;

		"Fibonacci számsorozat")
		   echo "Hány számot szeretnél legenerálni a sorozatból?"
		    read n
		   function fib
		   {
    		     x=0
		     y=1
		     i=2
		     echo "Fibonacci számsorozat eddig a számig $n :"
		     echo "$x"
		     echo "$y"
		     while [ $i -lt $n ]
		     do
			i=`expr $i + 1 `
			z=`expr $x + $y `
			echo "$z"
			x=$y
			y=$z
		     done
		    }
		    r=`fib $n`
		    echo "$r"
		     ;;

		"Négyszög rajzoló")
		  read -p "Add meg a négyszög nagyságát(minimum 4): " size
		  clear
		  for (( i = 1; i <= size; i++ )); do
		    for (( j = 1; j <= size; j++ )); do
		      if (( 1 == i || size == 1 || 1 == j || size == j )); then
			  echo -n "*"
			else
			  echo -n " "
		      fi
		      done
		      echo
		     done
		     ;;

		"Kilépés")
		   break
		     ;;
		*) echo "invalid option $REPLY";;
	      esac
	     done

